version: 2

builds:
- main: ./cmd/cloudwatch_metrics_proxy/
  binary: cloudwatch_metrics_proxy
  flags: -a -tags netgo
  ldflags: |
    -s -w
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
nfpms:
  -
    package_name: cloudwatch-metrics-proxy
    file_name_template: 'cloudwatch-metrics-proxy_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    homepage: https://github.com/mtanda/cloudwatch_metrics_proxy
    maintainer: Mitsuhiro Tanda
    description: cloudwatch read adapter
    license: Apache 2.0
    formats:
      - deb
    bindir: /usr/local/bin
    contents:
      - src: "packaging/deb/etc/default/cloudwatch_metrics_proxy"
        dst: "/etc/default/cloudwatch_metrics_proxy"
        type: config
      - src: "packaging/deb/systemd"
        dst: "/usr/lib/systemd/system"
    scripts:
      postinstall: "packaging/scripts/postinstall.sh"
      postremove: "packaging/scripts/postremove.sh"
      preremove: "packaging/scripts/preremove.sh"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^cut:'
    - '^typo'
