required = ["github.com/grpc-ecosystem/grpc-gateway/runtime"]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "=v1.6.3"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "=v1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/prometheus/tsdb"
  version = "v0.4.0"

[[constraint]]
  name = "github.com/prometheus/prometheus"
  version = "v2.7.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.16.30"
