required = ["github.com/grpc-ecosystem/grpc-gateway/runtime"]

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "=v1.3"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/prometheus/tsdb"
  revision = "c848349f07c83bd38d5d19faa5ea71c7fd8923ea"

[[constraint]]
  name = "github.com/prometheus/prometheus"
  version = "v2.3.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.14.18"
